config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "pages#home", as: :home
  get "about", to: "pages#about", as: :about
  get "up" => "rails/health#show", as: :rails_health_check

  resources :ingredients
  resources :products do
    resources :product_sizes, only: [:show, :new, :create, :edit, :update, :destroy]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
end

app/models/preparation.rb
class Preparation < ApplicationRecord
  belongs_to :recipe
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_sizes, dependent: :destroy
  validates :name, presence: true
  validates :product_type, presence: true
  accepts_nested_attributes_for :product_sizes
  CATEGORIES = ["Biscuits", "Tortas", "Moldes", "Galletas", "Helados", "Ediciones Especiales"]

end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  has_one :recipe, dependent: :destroy
  validates :size, uniqueness: { scope: :product_id, message: "ya existe para este producto" }

  SIZES = ["Personal", "Mediana", "Grande"]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :product_size
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :preparations
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to @ingredient
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient
    else
      render :edit
    end
  end

  def destroy
    Rails.logger.debug "Entrando al método destroy"
    @ingredient.destroy
    redirect_to ingredients_path, status: :see_other
  end

  private

  def ingredient_params
      params.require(:ingredient).permit(:name, :cost_per_gram, :supplier)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end
end

app/controllers/product_sizes_controller.rb
class ProductSizesController < ApplicationController
  before_action :set_product_size, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:new, :create, :show, :edit, :update, :destroy]

  def index
    @product_sizes = ProductSize.all
  end

  def show
  end

  def new
    @product_size = @product.product_sizes.build
  end

  def create
    @product_size = @product.product_sizes.build(product_size_params)
    if @product_size.save
      redirect_to product_product_size_path(@product, @product_size)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product_size.update(product_size_params)
      redirect_to product_product_size_path(@product, @product_size)
    else
      render :edit
    end
  end

  def destroy
    @product_size.destroy
    redirect_to product_path(@product), notice: 'Product size was successfully destroyed.'
  end

  private

  def product_size_params
    params.require(:product_size).permit(:size, :cost, :price, :product_id)
  end

  def set_product_size
    @product_size = ProductSize.find(params[:id])
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    @product.product_sizes.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def product_params
      params.require(:product).permit(:name, :product_type, :details, product_sizes_attributes: [:id, :size, :cost, :price])
  end

  def size_params
    params.require(:product).permit(:size)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/_form.html.erb
<h1>
  Agrega un nuevo ingrediente
</h1>
<% if @ingredient.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

    <ul>
    <% @ingredient.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @ingredient do |f| %>
  <%= f.input :name, label: 'Nombre' %>
  <%= f.input :cost_per_gram, label: 'Costo por gramo' %>
  <%= f.input :supplier, label: 'Proveedor' %>
  <%= f.button :submit, class: "btn btn-primary " %>
<% end %>
<%= link_to "Home", home_path, class: "btn btn-primary" %>

app/views/ingredients/edit.html.erb
<div class="container">
    <%= render "form", ingredient: @ingredient %>
</div>

app/views/ingredients/index.html.erb
<div class="container">
  <% if @ingredients.size > 0 %>
    <h1>Lista de ingredientes disponibles</h1>
  <% else %>
    <h1>No hay ingredientes disponibles</h1>
    <button>
      <%= link_to "Crear ingrediente", new_ingredient_path, class: "btn btn-primary" %>
    </button>
  <% end %>

  <ul>
    <% @ingredients.each do |ingredient| %>
      <li>
        <%= link_to ingredient.name, ingredient_path(ingredient) %>
      </li>
    <% end %>
  </ul>
  <%= link_to "Crear ingrediente", new_ingredient_path, class: "btn btn-primary" %>
  <%= link_to "Home", home_path, class: "btn btn-primary" %>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <%= render "form", ingredient: @ingredient %>
</div>

app/views/ingredients/show.html.erb
<div class="container">

  <h2><%= @ingredient.name %></h2>
    <p><%= @ingredient.supplier %></p>
  <p><%= @ingredient.cost_per_gram %></p>

  <div class="d-flex align-content">
    <%= link_to "Volver", ingredients_path, class: "btn btn-primary" %>
    <%= link_to "Editar", edit_ingredient_path(@ingredient), class: "btn" %>
    <%# Delete not working  %>
    <%#= link_to 'Delete', ingredient_path(@ingredient), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bakbak</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our first view 🚀</h1>

app/views/pages/home.html.erb
<div class="container">
  <h1>Bak Bak 🚀</h1>
</div>
<div class="container">
  <div class="card">
    <div class="card-body">
      <%= link_to("Ingredientes", ingredients_path) %>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <%= link_to("Productos", products_path) %>
    </div>
  </div>
</div>

app/views/product_sizes/_form.html.erb
<h1>
  Agrega un nuevo tamaño
</h1>
<% if @product_size.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product_size.errors.count, "error") %> prohibited this product size from being saved:</h2>

    <ul>
    <% @product_size.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for [@product, @product_size] do |f| %>
  <%= f.input :size, collection: ProductSize::SIZES, prompt: "Selecciona un tamaño" %>
  <%= f.input :price, label: 'Precio' %>
  <%= f.input :cost, label: 'Costo' %>
  <%= f.button :submit, class: "btn btn-primary " %>
<% end %>
<%= link_to "Home", home_path, class: "btn btn-primary" %>

app/views/product_sizes/edit.html.erb
<div class="container">
  <%= render "form", product_size: @product_size %>
</div>

app/views/product_sizes/new.html.erb
<div class="container">
  <%= render "form", product_size: @product_size %>
</div>

app/views/product_sizes/show.html.erb
<div class="container">

  <h1><%= @product_size.product.name %></h1>
  <p><%= @product_size.size %></p>
  <p><%= @product_size.price %></p>
  <p><%= @product_size.cost %></p>

  <div class="d-flex align-content">
    <%= link_to "Volver", product_path(@product), class: "btn btn-primary" %>
    <%= link_to "Editar", edit_product_product_size_path(@product, @product_size), class: "btn btn-secondary" %>
    <%= link_to 'Delete Product Size', product_product_size_path(@product, @product_size),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this product size?' },
              class: "btn btn-secondary" %>
  </div>

</div>

app/views/products/_form.html.erb
<h1>
  Agrega un nuevo producto
</h1>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @product do |f| %>
  <%= f.input :name, label: 'Nombre' %>
  <%= f.input :product_type, collection: Product::CATEGORIES, label: "Tipo de producto"%>
  <%= f.input :details, label: 'Detalles' %>

  <%= f.fields_for :product_sizes do |ps| %>
    <%= ps.input :size, collection: ProductSize::SIZES, prompt: "Selecciona un tamaño" %>
    <%= ps.input :cost %>
    <%= ps.input :price %>
  <% end %>

  <%= f.button :submit, class: "btn btn-primary " %>
<% end %>
<%= link_to "Home", home_path, class: "btn btn-primary" %>

app/views/products/edit.html.erb
<div class="container">
  <%= render "form", product: @product %>
</div>

app/views/products/index.html.erb
<div class="container">
  <% if @products.size > 0 %>
    <h1>Lista de productos disponibles</h1>
  <% else %>
    <h1>No hay productos disponibles</h1>
  <% end %>

  <ul>
    <% @products.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %>
      </li>
    <% end %>
  </ul>
  <%= link_to "Crear producto", new_product_path, class: "btn btn-primary" %>
  <%= link_to "Home", home_path, class: "btn btn-primary" %>
</div>

app/views/products/new.html.erb
<div class="container">
  <%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<div class="container">

  <h1><%= @product.name %></h1>
  <p><%= @product.product_type %></p>
  <p><%= @product.details %></p>

  <% @product.product_sizes.each do |ps| %>
    <%= link_to "#{ps.size}" , product_product_size_path(@product, ps)  %>
  <% end %>


  <div class="d-flex align-content">
    <%= link_to "Volver", products_path, class: "btn btn-primary" %>
    <%= link_to "Agregar nuevo tamaño", new_product_product_size_path(@product), class: "btn btn-primary" %>
    <%= link_to "Editar", edit_product_path(@product), class: "btn btn-secondary" %>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>